---
- name: Resistry and when usage inside playbook
  hosts: myservers
    # become: true      ==> required if host server is not a root user
  tasks:
    - name: Displaying files in home directory of target servers
      shell: "ls"
      register: output_ls
    
    - debug:
        var: output_ls
   
    - name: copt 1.yml if 1.yml is present in myservers
      copy:
        src: 1.yml
        dest: /root/1.yml
      when: output_ls.stdout == "1.yml"

